// Категорії продуктів — англійська → українська
export const categoryMap = {
  All: "Усі",
  Vegetable: "Овочі",
  Fruit: "Фрукти",
  Grain: "Злаки",
  Meat: "М'ясо",
  Dairy: "Молочне",
  Drink: "Напої",
  Soup: "Страви",
  Sweet: "Солодке",
};

// Прийоми їжі — українська → англійська (для збереження)
export const mealTypeMap = {
  Сніданок: "Breakfast",
  Обід: "Lunch",
  Вечеря: "Dinner",
  Перекус: "Snack",
};

// Прийоми їжі — англійська → українська (для відображення)
export const mealTypeReverseMap = {
  breakfast: "Сніданок",
  lunch: "Обід",
  dinner: "Вечеря",
  snack: "Перекус",
};

// Продукти — англійська → українська
export const productMap = {
  Tomato: "Помідор",
  Cucumber: "Огірок",
  Carrot: "Морква",
  Broccoli: "Броколі",
  Cabbage: "Капуста",
  Zucchini: "Кабачок",
  "Bell Pepper": "Болгарський перець",
  Eggplant: "Баклажан",
  Spinach: "Шпинат",
  Beetroot: "Буряк",
  "Green Beans": "Зелена квасоля",
  "Corn (boiled)": "Кукурудза (варена)",
  "Pickled Cucumbers": "Мариновані огірки",
  Onion: "Цибуля",
  Garlic: "Часник",
  Banana: "Банан",
  Apple: "Яблуко",
  Orange: "Апельсин",
  Pear: "Груша",
  Grapes: "Виноград",
  Watermelon: "Кавун",
  Melon: "Диня",
  Kiwi: "Ківі",
  Mango: "Манго",
  Pineapple: "Ананас",
  Blueberries: "Чорниця",
  Strawberries: "Полуниця",
  Avocado: "Авокадо",
  Pomegranate: "Гранат",
  Figs: "Інжир",
  "Bread (white)": "Білий хліб",
  "Bread (whole grain)": "Цільнозерновий хліб",
  "Rye Bread": "Житній хліб",
  "Pasta (boiled)": "Макарони варені",
  "Boiled Rice": "Рис варений",
  "Buckwheat (boiled)": "Гречка варена",
  Oatmeal: "Вівсянка",
  "Barley Porridge": "Ячна каша",
  "Millet Porridge": "Пшоняна каша",
  Cornflakes: "Кукурудзяні пластівці",
  Granola: "Гранола",
  Croissant: "Круасан",
  Muffin: "Маффін",
  "Fried Chicken Breast": "Куряча грудка смажена",
  "Grilled Pork Chop": "Свинина гриль",
  "Boiled Beef with Vegetables": "Яловичина з овочами",
  "Fried Fish Fillet": "Рибне філе смажене",
  "Baked Salmon with Lemon": "Запечений лосось",
  "Tuna Salad with Corn": "Салат з тунцем",
  "Stewed Liver with Onion": "Печінка тушкована",
  Ham: "Шинка",
  Sausage: "Ковбаса",
  Egg: "Яйце",
  "Boiled Egg": "Яйце варене",
  Milk: "Молоко",
  Cheese: "Сир",
  "Cottage Cheese": "Творог",
  Yogurt: "Йогурт",
  "Greek Yogurt": "Грецький йогурт",
  "Sour Cream 15%": "Сметана 15%",
  "Processed Cheese": "Плавлений сир",
  Water: "Вода",
  Tea: "Чай",
  Coffee: "Кава",
  "Juice (orange)": "Сік апельсиновий",
  "Coca-Cola": "Кока-Кола",
  Milkshake: "Молочний коктейль",
  Smoothie: "Смузі",
  "Protein Shake": "Протеїновий коктейль",
  Kvass: "Квас",
  "Mashed Potato": "Пюре картопляне",
  "Fried Potato": "Картопля смажена",
  "Baked Potato with Cheese": "Картопля з сиром",
  "Buckwheat with Gravy": "Гречка з підливою",
  "Rice with Chicken": "Рис з куркою",
  "Fried Rice with Vegetables": "Рис з овочами",
  "Macaroni with Cheese": "Макарони з сиром",
  "Pelmeni with Sour Cream": "Пельмені зі сметаною",
  "Chicken Cutlet with Buckwheat": "Котлета з гречкою",
  "Chicken Soup": "Курячий суп",
  Borscht: "Борщ",
  "Lentil Soup": "Суп з сочевиці",
  "Stuffed Cabbage Rolls": "Голубці",
  "Vegetable Stew": "Овочеве рагу",
  Chocolate: "Шоколад",
  Candy: "Цукерка",
  Cookie: "Печиво",
  "Cheesecakes with Raisins": "Сирники з родзинками",
  "Syrniki with Sour Cream": "Сирники зі сметаною",
  "Pancakes with Jam": "Млинці з варенням",
  Jam: "Варення",
  Honey: "Мед",
};

export const allergenMap = {
  lactose: "Лактоза",
  gluten: "Глютен",
  nuts: "Горіхи",
  eggs: "Яйця",
  fish: "Риба",
  soy: "Соя",
  shellfish: "Морепродукти",
  sesame: "Кунжут",
  mustard: "Гірчиця",
  celery: "Селера",
  peanuts: "Арахіс",
};
